### ISSUE TITLE
Support for YAML meta data header

### ISSUE THREAD

**Issue by MaxNoe** [euclio/vim-markdown-composer#11]
Pandoc uses yaml meta data headers like these:

``` markdown

---
title: My awesome document
date: 206-02-25
author: John Doe

---

# Introduction

```

Would be great if this was ignored for rendering.
Right now the last line gets rendered as `h2`

**Comment by euclio** [comment]
I'm sympathetic to the issue (I use YAML metadata quite often actually), but I'm wary to include anything that isn't standardized across markdown parsers. Last I checked CommonMark doesn't specify anything about metadata. I'll consider putting this behind an option.

**Comment by MaxNoe** [comment]
Github for example shows this as table on top.

**Comment by Cutuchiqueno** [comment]
definitely +1 from my side.

However, I think there is a broader topic behind this which is the question of different markdown dialects.

Personally, I write my whole PhD in pandoc markdown which is the best choice for academic writing in markdown I would argue. Markdown-composer was the one thing I always waited for. However, there are some things which appear quiet often in academic texts like citations (`[@CITATIONKEY]`)which are not supported by classic markdown and by this plugin.

Unnecessary to say that of cause I would love to these things in vim-markdown-composer

**Comment by euclio** [comment]
What if the plugin provided a way to change the markdown backend (i.e., `--backend=cmark`, `--backend=pandoc`)? What pandoc options would need to be supported?

**Comment by Cutuchiqueno** [comment]
the possibility to change the backend would be a fine solution, especially in the latter suggestion where you can set your flags and options the way you want.

Especially, for longer texts this could be important. For instance, cite keys shouldn't be parsed for longer texts. Othervise, there would probably a huge delay in the transformation. Or is the life preview changed incrementally?

Looking forward to it
