### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by teto** [euclio/vim-markdown-composer#18]
I use latest everything python-neovim 0.1.9, neovim add41dc , and latest vim-markdown-composer:
I run in this problem:

```
error caught in async handler '/home/teto/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer:autocmd:TextChanged,TextChangedI:*.m
d,*.mkd,*.markdown []'                                                                                                                                     
Traceback (most recent call last):                                                                                                                         
  File "/home/teto/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer/__init__.py", line 135, in send_current_buffer_autocmd     
    self.send_current_buffer()                                                                                                                             
  File "/home/teto/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer/__init__.py", line 42, in send_current_buffer              
    self._send_request('send_data', '\n'.join(self.vim.current.buffer))                                                                                    
  File "/home/teto/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer/__init__.py", line 121, in _send_request                   
    self.client.stdin.write(msg)                                                                                                                           
BrokenPipeError: [Errno 32] Broken pipe
```

with a markdown file. When I tried opening it in a separate neovim instance it would work fine. Can the pipe be broken because my computer hibernated ?

**Comment by euclio** [comment]
Hm, the rust subprocess probably crashed for whatever reason.

**Comment by NickHu** [comment]
I also had this issue and can confirm that using f30196b651d941ad38dffcda251727bbf1e2c106 fixed the problem.

**Comment by euclio** [comment]
@NickHu are you saying that upgrading or downgrading to that commit fixed it?

**Comment by NickHu** [comment]
@euclio Downgrading to that commit from master (d0579d1b6136ad04addef68b7968f3936aad2a59)
I would suspect the regression to have come from c4fb795cae0ab84365cb538646abc5d2d93bfe39.

**Comment by euclio** [comment]
Bummer. Are you seeing the issue in normal use or just after hibernating your computer?

**Comment by NickHu** [comment]
Normal use - opening a markdown file just straight up doesn't open a window, and it seems like the rust server immediately crashes from `ps aux` too.

**Comment by euclio** [comment]
Thank you for the info. I'll do some debugging tonight.

**Comment by euclio** [comment]
@NickHu Keeping this bug open in case this behavior is observed in other scenarios, but the fix I just pushed should address normal usage.

**Comment by teto** [comment]
using neovim 0.1.5 with current master,
```
error caught in async handler '/home/teto/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer:autocmd:BufEnter:*.md,*.mkd,*.markdown []'  
Traceback (most recent call last):                                                                                                                                 
  File "/home/teto/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer/__init__.py", line 131, in change_working_directory                
    self._send_request('chdir', current_dir)                                                                                                                       
  File "/home/teto/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer/__init__.py", line 122, in _send_request                           
    self.client.stdin.write(msg)                                                                                                                                   
BrokenPipeError: [Errno 32] Broken pipe   
```

**Comment by scottgrayson** [comment]
I'm getting the same error as @teto

**Comment by tomeustace** [comment]
I'm seeing same as @teto also.  neovim 0.1.6-dev.

**Comment by euclio** [comment]
@teto @scottgrayson @tomeustace 

Could you give me some steps to reproduce? I'll look into this again.

**Comment by tomeustace** [comment]
1. vim file.md
2  enter insert mode
3. type any character to see error

I'm using Ubuntu 14.04.  If there is any more environment detail you need let me know.

**Comment by euclio** [comment]
Rust, Python and vim version would be helpful as well!

**Comment by tomeustace** [comment]
rustc 1.6.0 (c3ob771ad 2016-01-19)
has("python3") = 1 
NVIM 0.1.6-dev

attached profile file shows output where I open a .md file and enter insert mode, the close file.
Hopefully it will help.  If you need anything else let me know.

[vim-markdown-broken-pipe.txt](https://github.com/euclio/vim-markdown-composer/files/528250/vim-markdown-broken-pipe.txt)

**Comment by euclio** [comment]
@tomeustace I fear that version of Rust is too old. Can you try with the latest stable? You can install it easily with [rustup.rs](http://rustup.rs).

**Comment by euclio** [comment]
This should be fixed in the latest version, as the Python dependency has been dropped.

**Comment by tomeustace** [comment]
Thanks, after upgrade all good.
