### ISSUE TITLE
Question: how to use pandoc to generate the markdown preview?

### ISSUE THREAD

**Issue by Alok** [euclio/vim-markdown-composer#21]
I use pandoc's flavor of markdown, and not all its features render correctly in the preview. Is there a way to make pandoc the processor so it can generate the correct HTML?

**Comment by euclio** [comment]
Hi @Alok, right now there is no way to make pandoc the markdown engine, but I may add the feature in the future as it has been requested a number of times.

**Comment by euclio** [comment]
Closing as duplicate of #25.
