### ISSUE TITLE
Custom CSS support

### ISSUE THREAD

**Issue by maxigaz** [euclio/vim-markdown-composer#23]
I’ve noticed that [aurelius has initial CSS support](https://github.com/euclio/aurelius/issues/1). I wonder if it’s possible to use a CSS file for Markdown Composer. (I’d like to have a dark background with light text in all previews.)

**Comment by euclio** [comment]
Hi @maxigaz, I'm working on this currently. Still working out the design on how to support URLs and local paths transparently.
