### ISSUE TITLE
Provide an example gif

### ISSUE THREAD

**Issue by roblabla** [euclio/vim-markdown-composer#26]
It'd be nice to see what it looks like, like https://github.com/suan/vim-instant-markdown :)

**Comment by euclio** [comment]
Hm, there is a link in the README. Not sure why it isn't showing up anymore!

**Comment by euclio** [comment]
It appears that the image has to be hosted in the repository to get around this. I need to record a new gif anyways :)

**Comment by euclio** [comment]
Fixed in 04fdd4a by using a smaller gif. Seems like the limit is around 5MB.
