### ISSUE TITLE
High CPU usage when refreshing browser page

### ISSUE THREAD

**Issue by Nemo157** [euclio/vim-markdown-composer#27]
If I refresh the webpage the preview is shown in, then the `markdown-composer` process CPU usage goes really high. Just closing the page doesn't cause this, it happens when a new instance of the page is opened. It also occurs if I open a second copy of the page in a new browser.

**Comment by euclio** [comment]
Hm, possibly related to websockets, but having trouble finding a root cause.

**Comment by euclio** [comment]
I'm not seeing this issue anymore in the latest version. Feel free to reopen if you're still experiencing it.
