### ISSUE TITLE
Error on "cargo build --release"

### ISSUE THREAD

**Issue by utkuufuk** [euclio/vim-markdown-composer#29]
I'm using Neovim with vim-plug on Ubuntu. I get the error:
```
failed to parse registry's information for: serde

Caused by:
  the given version requirement is invalid
```

 when I run
```
cargo build --release --verbose
```

I have installed rust and cargo:
```
curl https://sh.rustup.rs -sSf | sh
apt install cargo
```

At the beginning of ```~/.config/nvim/init.vim``` file, I placed the following:
```
" Plugins will be downloaded under the specified directory.
call plug#begin('~/.config/nvim/plugged')

function! BuildComposer(info)
  if a:info.status != 'unchanged' || a:info.force
    if has('nvim')
      !cargo build --release
    else
      !cargo build --release --no-default-features --features json-rpc
    endif
  endif
endfunction

Plug 'euclio/vim-markdown-composer', { 'do': function('BuildComposer') }
```
I'm new to both linux and vim, so it's possible that I'm doing something wrong.

**Comment by utkuufuk** [comment]
Ok I tried to uninstall and reinstall rust. This time I didn't install cargo explicitly. Now when I try
```
cargo build --release --verbose
```
I get
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to open: /home/utku/.config/nvim/plugged/vim-markdown-composer/target/release/.cargo-lock

Caused by:
  Permission denied (os error 13)
```

**Comment by euclio** [comment]
Hm, I think you're on the right track. Have you tried `rm -rf ~/.config/nvim/plugged/vim-markdown-composer` and reinstalling the plugin?

**Comment by utkuufuk** [comment]
I tried what you suggested. When I run ```:PlugInstall```, I got:
```
/bin/bash: cargo: command not found
shell returned 127
```

**Comment by utkuufuk** [comment]
Well, as it turns out, I had created the ```~/.config/nvim/``` directory for the root user to begin with.
```sudo chown -R utku:utku ~/.config/nvim/``` did the trick. 
Sorry for the trouble, as I told before, I am __very__ new to Linux :)

**Comment by euclio** [comment]
No problem! Hope you enjoy the plugin :)
