### ISSUE TITLE
embedded image not displaying

### ISSUE THREAD

**Issue by liujoey** [euclio/vim-markdown-composer#3]
embedded image not showing, e.g. `![Figure 1-1](images/overview.png)`

**Comment by euclio** [comment]
Hey @liujoey, just letting you know I haven't forgotten about this. The way that Nickel handles StaticFiles middleware means that I can't change the folder that static files are served from at runtime with the current architecture. I'm working on a solution.

**Comment by liujoey** [comment]
@euclio Great. Thank you for the effort, I understand it's not something easy to do.

**Comment by euclio** [comment]
Opened nickel-org/nickel.rs#307.
