### ISSUE TITLE
No job_start in earlier versions of vim

### ISSUE THREAD

**Issue by sarahscheffler** [euclio/vim-markdown-composer#30]
I originally tried to use this in vim 7.4.898 (this is apparently still default in OSX Sierra), but that failed when opening a .md file on line 43 of `composer.vim` with the error `E117: Unknown function: job_start`.

Updating to Vim 8.0 fixed the problem, but maybe this should be documented somewhere?  (I'm not sure about versions between 7.4 and 8.0, if there are any.)

**Comment by euclio** [comment]
Ah, whoops, I totally had this in an earlier revision on the README, but I guess I never actually committed it. Yeah, Vim 8 is required.
