### ISSUE TITLE
Failed to parse registry's information for: serde

### ISSUE THREAD

**Issue by lwm** [euclio/vim-markdown-composer#33]
``` bash
λ ~/.config/nvim/plugged/vim-markdown-composer/ master cargo build --release --verbose
failed to parse registry's information for: serde
Caused by:
  the given version requirement is invalid
```

**Comment by euclio** [comment]
I'm unable to reproduce on the latest nightly and stable. Perhaps try updating Rust and `cargo clean`?

**Comment by lwm** [comment]
Hey, thanks for taking a look! I don't really know about Rust but are my versions way behind latest?

```
λ ~/.config/nvim/plugged/vim-markdown-composer/ master rustc --version
rustc 1.7.0
λ ~/.config/nvim/plugged/vim-markdown-composer/ master cargo --version
cargo 0.8.0 (built 2016-03-22)
```

**Comment by euclio** [comment]
Yes, the version on apt-get is too old for use by `vim-markdown-composer`. You can try installing with https://rustup.rs which will let you install the newest stable easily.

**Comment by lwm** [comment]
Ah! I see it in the README.md now as well, doh! Thanks! :smile:
