### ISSUE TITLE
Unable to open markdown preview when g:markdown_composer_open_browser = 0

### ISSUE THREAD

**Issue by alloro** [euclio/vim-markdown-composer#41]
I've set *g:markdown_composer_open_browser = 0* in my nvim/init.vim. 
After opening the markdown file the call to *:ComposerOpen* does not open the preview.

**Comment by euclio** [comment]
I've identified the issue. It's a hang on Listening::send when there are no active websocket connections.

**Comment by alloro** [comment]
Still have the same issue after updating the plugin.

Used config settings:
`
let g:markdown_composer_autostart = 1
`
`
let g:markdown_composer_open_browser = 0
`
Even without the autostart setting, _ComposerStart_ and _ComposerOpen_ has no effect.

**Comment by euclio** [comment]
I'm unable to reproduce the issue after the fix. Maybe try removing the plugin and reinstalling?

**Comment by alloro** [comment]
After reistalling and executing "cargo build --release" in the plugin folder everything worked.
