### ISSUE TITLE
Error detected while processing function <SNR>89_startServer

### ISSUE THREAD

**Issue by gorliver** [euclio/vim-markdown-composer#42]
Hi,
I got this error when opening a markdown file:
Error detected while processing function <SNR>89_startServer:
line   59:
E475: Invalid argument: cwd
I use vim 8.0 and cargo build Finished without any issue.

**Comment by euclio** [comment]
Hi, what's your exact vim version? This should be fixed by using vim 8.0.0902 or greater.

**Comment by gorliver** [comment]
I installed the newest vim 8.0.1207 and it works perfectly!
Thank you!

**Comment by euclio** [comment]
Great! No problem :)
