### ISSUE TITLE
Invalid argument: cwd

### ISSUE THREAD

**Issue by nrupatunga** [euclio/vim-markdown-composer#43]
After updating the plugin, getting the follow error. 
![markdown-error](https://user-images.githubusercontent.com/980580/32220020-2baec1ac-be56-11e7-9106-f3d237e06f94.jpg)

Any solution?

**Comment by sarahscheffler** [comment]
I think this is a Vim vs Neovim issue.  I had the same problem after updating on Vim 8.0.  After switching to Neovim, this problem went away.  (Though I now seem to have an unrelated channel bug that I'll make a separate issue on.)

For now, I fixed the problem by reverting to a previous commit 120c2dfc05fca4d1dbdb4be1be477d653e969458 .

**Comment by euclio** [comment]
Ah, sorry, forgot to respond to this! This was reported in #42 as well. You can fix it by using neovim or upgrading your vim version.
