### ISSUE TITLE
Many hightlight.js themes are missing (g:markdown_composer_syntax_theme)

### ISSUE THREAD

**Issue by maximbaz** [euclio/vim-markdown-composer#51]
The documentation says:

```
g:markdown_composer_syntax_theme        *g:markdown_composer_syntax_theme*
            The theme that the preview should use for syntax highlighting. All
            themes from highlight.js are supported. A demo can be found at
            https://highlightjs.org/static/demo/.

            The variable should be the name of the theme's stylesheet (without
            .css). The stylesheets may be found at

            https://github.com/isagalaev/highlight.js/tree/master/src/styles
```

I tried to use `gruvbox-dark` and found that it is missing, tried a few others and they are missing too. I noticed that `solarized-dark` should actually be named `solarized_dark` to be working.

Is it just a matter of updating the highlight.js dependency to synchronize the list of themes, or something else is broken?

**Comment by technetos** [comment]
Are these themes stored locally or pulled in at runtime?

**Comment by maximbaz** [comment]
`highlight.js` is indeed changing only the theme of `<code>` blocks, nothing else. However you can notice that the rest of the document is still rendered in a style that is quite different from GitHub, although it is promised to have exactly the same style.

The reason is https://github.com/euclio/aurelius/issues/10, another dependency [github-markdown-css](https://github.com/sindresorhus/github-markdown-css/releases) hasn't been updated for the past 3 years and it's nothing we can do ourselves, we have to wait for @euclio to update the dependencies to get the latest style.

**Comment by euclio** [comment]
I'm currently working on this. Plan to push the update within a few days.

**Comment by maximbaz** [comment]
@euclio thanks for the update! One final bit, I noticed that you use your own fork of github-markdown-css where you adjust some styles. I just tested and it seems like your adjustment is no longer needed, I tried a couple of themes with highlight.js and they work just fine. Your adjustment actually breaks highlighting inline code blocks `like this one`. Do you have an example of when your fork works better with highlight.js? If no, perhaps you should consider using the upstream directly as a dependency 🙂

**Comment by euclio** [comment]
@maximbaz IIRC I forked it because the GitHub styles used to override the highlight.js ones. If that's the case, I'd be glad to switch to upstream!
