### ISSUE TITLE
Rust 1.3 / 1.4 no longer supported

### ISSUE THREAD

**Issue by FvD** [euclio/vim-markdown-composer#6]
In the readme you state "it should work in versions as early as 1.3. " but the latest update has issues with a dependency that is not compiling in earlier versions of rust-lang.

```
~/.c/n/p/vim-markdown-composer ❯❯❯ cargo build --release  
   Compiling unicase v1.1.0
/home/frans/.cargo/registry/src/github.com-0a35038f75765ae4/unicase-1.1.0/src/lib.rs:55:20: 55:36 error: use of unstable library feature 'iter_order': needs review and revision (see issue #27737)
/home/frans/.cargo/registry/src/github.com-0a35038f75765ae4/unicase-1.1.0/src/lib.rs:55         self_chars.cmp(other_chars)

error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `unicase`.
```

The ticket this is refering to [#27737 in rust-lang](https://github.com/rust-lang/rust/issues/27737) that was fixed and updating to the latest stable release (1.5) solves the unicase compile issue. Consider updating the documentation.

**Comment by euclio** [comment]
Thanks!
