### ISSUE TITLE
configure path to binary (or ignore it)

### ISSUE THREAD

**Issue by teto** [euclio/vim-markdown-composer#69]
Due to how nixos works, I have to install the rust component outside of the vim plugin. I gues I could create a symlink  but assuming the binary in PATH or allowing to set the path to it would be nice.
Currently, it seems like the path to the binary is hardcoded:
https://github.com/euclio/vim-markdown-composer/blob/61a0ba176a420ca6c0c5fd3d41b47685acb010f9/after/ftplugin/markdown/composer.vim#L15-L16

**Comment by ok-nick** [comment]
Doesn't seem like this issue will be resolved any time soon, but I have run into this issue. My cargo target folder is set by default to a global folder so `cargo build` doesn't compile directly into the project folder. I could do some workarounds, like setting the target dir environment variable, but that will affect everything globally.
