### ISSUE TITLE
Javascript over unencrypted http

### ISSUE THREAD

**Issue by vorner** [euclio/vim-markdown-composer#79]
Hello

According to no-script extension, the opened page downloads and runs some javascript from cloudflare.com. This is done through plain http. As there are records of various entities modifying and injecting malicious code to http content in-flight, this is potentially dangerous. Is it possible to switch to https for these scripts?

(What does the script do anyway? It seems the preview works just fine if I forbid executing this script)

**Comment by euclio** [comment]
Yep, this should definitely be fixed. The cloudflare scripts are for KaTeX support. I've been spending the holidays on aurelius updates so this will be fixed soon.
