### ISSUE TITLE
compilation error: aurelius

### ISSUE THREAD

**Issue by MeisterTea** [euclio/vim-markdown-composer#83]
Hi, I am getting this error:
```sh
   Compiling aurelius v0.7.1
error[E0658]: use of unstable library feature 'mem_take'
   --> /home/mistertea/.cargo/registry/src/github.com-1ecc6299db9ec823/aurelius-0.7.1/src/lib.rs:342:27
    |
342 |             let clients = std::mem::take(&mut *self.md_clients.lock().unwrap());
    |                           ^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/61129

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `aurelius`.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

vim-plug fails at installing the plugin but even if I try to install it by going inside of the directory and running `cargo build --release`, I am getting the error above

**Comment by euclio** [comment]
Try upgrading your Rust version to the latest stable compiler.

**Comment by ianchanning** [comment]
I got similar warnings because my Rust was out of date. It might be worth including a general 'if you get "use of unstable library feature" warnings to run `rustup update`. It's likely that people using this plugin either won't know or care about rust and that it will be out of date.
