### ISSUE TITLE
New instance of firefox, but no preview

### ISSUE THREAD

**Issue by EdmundsEcho** [euclio/vim-markdown-composer#90]
Hello, I have had this happen in the past and just plain forgot how I fixed it.  Are there preferences or settings that need to be enabled in order for the browser to accept and display the preview?  Also, is there a single address/port that I can pull up to view the preview?   I ask because when I do get it to work, if I close the tab/window/instance, I can't get it open again with a new `.md` file.  I'm just looking for advice.  The plugin works, I just have to get my browser and other understanding up and running :)) Thanks in advance.  \- E

**Comment by euclio** [comment]
It should open automatically by default. If you need to open a new window, you can use the `:ComposerOpen` command from vim. The window will close automatically if the websocket closes, so if the window closes immediately on open it might signal a crash in the plugin.

**Comment by EdmundsEcho** [comment]
Thank you
