### ISSUE TITLE
How to use base16 themes?

### ISSUE THREAD

**Issue by EPadronU** [euclio/vim-markdown-composer#95]
There are themes under the [base16](https://github.com/highlightjs/highlight.js/tree/main/src/styles/base16) directory that don't work when referencing them by their name (eg: `let g:markdown_composer_syntax_theme="ros-pine-moon"`.

I also tried to include the directory with no luck (eg: `let g:markdown_composer_syntax_theme="base16/ros-pine-moon"`

My workaround:
```lua
vim.g.markdown_composer_syntax_theme = "disabled"

vim.g.markdown_composer_custom_css = {
  vim.fn.expand("file://$HOME/.local/share/syntax-highlight-theme.css"),
}

```

**Comment by euclio** [comment]
Thanks for the report. Turns out the version of highlight.js was too old to have those themes. Updated to the latest version!
